trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '13.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
    echo ">>> Installation complete"
    yarn && yarn compile
    echo ">>> Compilation complete"
    yarn && yarn test
  displayName: 'Run Tests'