name: Test

on: [pull_request]

permissions: read-all

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Test

    # runs-on: ${{ matrix.os }}

    # strategy:
    #   fail-fast: false
    #   matrix:
    #     os: [macos-latest, windows-latest]
    #     node-version: [22.x]

    runs-on: ubuntu-latest

    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
      - name: Install dependencies and link
        run: npm ci
      - name: Package
        run: npm run build
      # - name: Run tests
      #   run: npm run wdio-test
