name: Test

on: [pull_request]

permissions: read-all

concurrency:
  group: ${{ github.ref_name }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, macos-13, windows-latest, windows-2022]
        node-version: [18.x, 20.x, 22.x]

    timeout-minutes: 15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
      - name: Install dependencies and link
        run: npm ci
      - name: Run tests
        run: npm run wdio-test
